trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(publishDir)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(publishDir)'
    ArtifactName: 'drop'

- task: AzureWebApp@1
  displayName: Deploy to Azure App Service
  inputs:
    azureSubscription: 'Azure subscription 1(1e01003a-b580-4209-a0ee-966441afc749)'
    appName: 'YOUR-APP-SERVICE-NAME'
    package: '$(publishDir)/*.zip'
